### ISSUE TITLE
after upgrading to CES 3.3, clicking on syslog menu bring to wrong page

### ISSUE THREAD

**Issue by trunet** [centreon/centreon-syslog-frontend#52]
I upgraded to CES 3.3 and now when I click Monitoring > Syslog, it brings me to the Monitoring  >  Performances  >  Graphs page on https://HOSTNAME/centreon/main.php?p=204

**Comment by trunet** [comment]
workaround on mysql:

   update topology set topology_page=205 where topology_id=216 and topology_name='Syslog';

**Comment by lpinsivy** [comment]
Yes Centreon web took Syslog topology, will be updated in v1.5.3
